### ISSUE TITLE
Process all challenges in one go

### ISSUE THREAD

**Issue by pwaring** [pwaring/letsencrypt.sh-djbdns#3]
At present the process is to fetch and verify each challenge sequentially. This works, but does result in delays whilst the script waits for DNS changes to make their way to all the nameservers for a domain (one delay per domain). A better solution for multiple domain requests would be to obtain all the challenges, upload them all to the nameservers and then verify them all. This would result in only one 'upload delay', regardless of the number of domains.

letsencrypt.sh can support this functionality, as outlined here:

https://github.com/lukas2511/letsencrypt.sh/issues/168

So it is a matter of changing the logic in the hook script to process all the challenges to support this behaviour. It can safely be made the default too, as it will speed things up for all cases other than a single domain certificate (which will be unchanged).

**Comment by ehuggett** [comment]
I was actually about to open an issue to ask if you would accept patches for this feature before taking the time to rewrite the 'working' version I have of this, I've been using it with the staging servers to get certificates with 100 SAN's.

You should be aware that you are limited to (300?) unfulfilled challenges (per account?) per week, so this can go wrong quite quickly! (a hook to run before letsencrypt.sh requests challenges so we can create and check a test record or exit with an error status would be nice... )

Additionally, what are you thoughts on adding and how to implement
- having the records written out to a file
- The ability to run additional script to do something with the file (for example, I have to rsync my tinydns config records to the authoritative server).

**Comment by pwaring** [comment]
For testing I use the staging server, which I don't think has a 300 challenges/week restriction. It still produces a certificate but they're not signed in the same way as production ones so they will cause a warning in clients:

https://github.com/lukas2511/letsencrypt.sh/blob/master/docs/staging.md

The other potential issue is that letsencrypt.sh puts all the challenges on a single command line, so you end up with 4 x the number of domains arguments for the `deploy_challenge` action. I don't know if this will exceed the maximum number of arguments allowed by either `argparse` or the shell.

Writing out to a file is something I would like to support, though I have not got as far as thinking about how it would work. I also rsync my config records (I use [Bytemark's content DNS](https://www.bytemark.co.uk/docs/domains/dnsc/)) so I have a vested interest in supporting that.

I would also like to write an Ansible module to complete the automation, though that is some way off.

**Comment by pwaring** [comment]
I've split the 'writing to a file' option out to another issue as it's a separate task to processing challenges in one step: #4

**Comment by ehuggett** [comment]
A little out of date, but the first mention of the pending challenges I could find again quickly (300 per account per week, may also apply to staging) https://community.letsencrypt.org/t/unexpected-registration-rate-limiting-error/2157/19 

This was a fortnight ago, so I might be mistaken, but I think I did hit the 300 unfulfilled challenge limit with the staging servers and I just deleted my letsencrypt.sh account and cert directories to try again (my modified script wasn't fulfilling the challenges successfully, it would error out after the first certificate and i got the rate limit error after a few failed attempts as I had specified 100 SANs on the failing certificate config).

I haven't run into any trouble with the maximum argument length so far

```
$ cat /etc/issue
Debian GNU/Linux stretch/sid \n \l

$ xargs --show-limits
Your environment variables take up 1818 bytes
POSIX upper limit on argument length (this system): 2093286
POSIX smallest allowable upper limit on argument length (all systems): 4096
Maximum length of command we could actually use: 2091468
Size of command buffer we are actually using: 131072
Maximum parallelism (--max-procs must be no greater): 2147483647
```

I had trouble with argparse and repeating positional arguments, I ended up taking this approach while making a mental note to look into it further http://stackoverflow.com/questions/27681718/using-python-argparse-on-repeating-groups . I did end up wondering if argparse perhaps isn't well suited to this use case?

Small world, I am also using Bytemarks content DNS! Using rsync manually (not the upload script they provide) I was able to "add" a file to the existing configuration, but I couldn't find a way to delete it without copying the remote config files to localhost, removing the file containing the challenges and syncing the entire directory back. I'm probably going to settle having rsync copy an empty file over it (as i can do this without a local copy of the config) in the cleanup hook action

**Comment by pwaring** [comment]
It does sound like `argparse` may not be ideal for this case - even with single hosts I had to use a workaround to deal with the fact that not all calls to the hook script have 4 arguments.

It sounds like this particular issue is going to require a bit more thought. My current plan is to fix #4 first as that will automate the whole process. It won't make requests with large number of hostnames quicker but it will mean that you can set the script running and then leave it in the background.

**Comment by ehuggett** [comment]
I've made my modified version public, most of the additions are to handle argparse and reshuffling what you had already done to handle HOOK_CHAIN

https://github.com/ehuggett/letsencrypt.sh-djbdns/commit/77321eaffd3dcb1126db076e399226e34d4cd4e6

**Comment by ehuggett** [comment]
A basic version of the "hook" has been added in a later commit

It doesn't support actions yet, but all that's needed is to pass it the current value of "action" that letsencrypt passed us.

I have NOT tested this with a real hook script yet, I just used this to check the script was being called and it could do something with the file path it was passed
```
#!/bin/bash
rsync $1 data/letsrsync.txt
```

**Comment by pwaring** [comment]
Apologies, I've let this project gather dust as I've moved away from DNS challenges, partly because I've worked out how to get HTTP challenges working and automated. As a result, I'm going to archive this repository shortly, though people are welcome to fork it under the terms of the licence.
